BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Favorite" (
	"favid"	INTEGER NOT NULL,
	"favfilm"	INTEGER NOT NULL,
	"user"	TEXT NOT NULL,
	PRIMARY KEY("favid" AUTOINCREMENT),
	FOREIGN KEY("favfilm") REFERENCES "Films"("id") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("user") REFERENCES "users"("Login") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Films" (
	"id"	INTEGER,
	"Path"	TEXT NOT NULL DEFAULT 'posters',
	"PosterFile"	TEXT NOT NULL,
	"Title"	TEXT NOT NULL,
	"Release"	TEXT NOT NULL,
	"Duration"	INTEGER NOT NULL,
	"Description"	TEXT,
	"Director"	TEXT NOT NULL,
	"Actors"	TEXT NOT NULL,
	"Studio"	TEXT NOT NULL,
	"Genres"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "users" (
	"Login"	TEXT NOT NULL UNIQUE,
	"Hash"	TEXT NOT NULL,
	"Admin"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("Login")
);
CREATE INDEX "films_title_index" ON "Films"("Title");
COMMIT;
